#ifndef _HEADER_INSIDE1_1_H_
#define _HEADER_INSIDE1_1_H_

#define HEADER_MACRO_INSIDE1_1_VALUE_0 0
#define HEADER_MACRO_INSIDE1_1_VALUE_1 1
#define HEADER_MACRO_INSIDE1_1_VALUE_2 2
#define HEADER_MACRO_INSIDE1_1_VALUE_3 3
#define HEADER_MACRO_INSIDE1_1_VALUE_4 4
#define HEADER_MACRO_INSIDE1_1_VALUE_5 5
#define HEADER_MACRO_INSIDE1_1_VALUE_6 6
#define HEADER_MACRO_INSIDE1_1_VALUE_7 7
#define HEADER_MACRO_INSIDE1_1_VALUE_8 8
#define HEADER_MACRO_INSIDE1_1_VALUE_9 9

#endif